sleep

diff --git a/.github/workflows/cp-pipeline-ci.yml b/.github/workflows/cp-pipeline-ci.yml
--- a/.github/workflows/cp-pipeline-ci.yml
+++ b/.github/workflows/cp-pipeline-ci.yml
@@ -27,7 +27,12 @@ jobs:
         run: |
           echo "Creating codespace for repo: $REPO at ref: $REF"
           gh codespace create --repo "$REPO" --branch "$REF" --devcontainer-path ".devcontainer/devcontainer.json" --display-name "$REF" --machine standardLinux32gb
+          sleep 10
           cs_id=$(gh codespace list --repo "$REPO" --json name,gitStatus --jq ".[] | select(.gitStatus.branch == \"$REF\") | .name" | head -n 1)
+          if [ -z "$cs_id" ]; then
+            echo "::error ::Codespace ID not found for branch $REF"
+            exit 1
+          fi
           echo "codespace_id=$cs_id" >> $GITHUB_OUTPUT
 
       - name: Verify Codespace Status
